# Generated by Django 4.0.4 on 2022-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=128)),
                ('option_one', models.CharField(max_length=128)),
                ('option_two', models.CharField(max_length=128)),
                ('option_three', models.CharField(max_length=128)),
                ('option_four', models.CharField(max_length=128)),
            ],
        ),
    ]
