# Generated by Django 4.0.4 on 2022-04-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
