# Generated by Django 4.0.4 on 2022-05-01 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_question_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answered', models.IntegerField()),
                ('correct_answeres', models.IntegerField()),
                ('wrong_answeres', models.IntegerField()),
                ('correct_percentage', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField()),
                ('win_rate', models.IntegerField()),
                ('money_earned', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
