# Generated by Django 4.0.4 on 2022-05-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_statistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'statistics'},
        ),
        migrations.AlterModelTable(
            name='statistics',
            table='web_statistics',
        ),
    ]
