# Generated by Django 4.0.4 on 2022-05-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_statistics_options_alter_statistics_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='correct_answeres',
            new_name='correct_answers',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='wrong_answeres',
            new_name='wrong_answers',
        ),
    ]
