# Generated by Django 4.0.4 on 2022-05-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'web_category',
            },
        ),
    ]
